# k8s/secrets.example.yaml (for GitHub)
apiVersion: v1
kind: Secret
metadata:
  name: google-oauth
  namespace: aegonish
type: Opaque
stringData:
  GOOGLE_DRIVE_FOLDER_ID: "your-folder-id-here"
  GOOGLE_CLIENT_ID: "your-client-id-here"
  GOOGLE_CLIENT_SECRET: "your-client-secret-here"
  GOOGLE_REDIRECT_URI: "https://developers.google.com/oauthplayground"
  GOOGLE_REFRESH_TOKEN: "your-refresh-token-here"
  MONGO_URI: "mongodb://mongo.aegonish.svc.cluster.local:27017/aegonish_blog"
  PORT: "4000"