#apiVersion: v1
#kind: Secret
#metadata:
#  name: google-oauth
#  namespace: aegonish
#  labels:
#    app.kubernetes.io/managed-by: Helm
#type: Opaque
#stringData:
#  GOOGLE_DRIVE_FOLDER_ID: {{ .Values.secrets.GOOGLE_DRIVE_FOLDER_ID | quote }}
#  GOOGLE_CLIENT_ID: {{ .Values.secrets.GOOGLE_CLIENT_ID | quote }}
#  GOOGLE_CLIENT_SECRET: {{ .Values.secrets.GOOGLE_CLIENT_SECRET | quote }}
#  GOOGLE_REDIRECT_URI: {{ .Values.secrets.GOOGLE_REDIRECT_URI | quote }}
#  GOOGLE_REFRESH_TOKEN: {{ .Values.secrets.GOOGLE_REFRESH_TOKEN | quote }}
#  MONGO_URI: {{ .Values.secrets.MONGO_URI | quote }}
#  PORT: {{ .Values.secrets.PORT | quote }}
